language: node_js
sudo: false
node_js:
  - 6

cache:
  directories:
    - node_modules

script:
  - npm i -g typings
  - typings install
  - npm run transpile
  - npm test

after_success: npm run coveralls

deploy:
  skip_cleanup: true
  provider: npm
  email: olegman.ru@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: router-async/router-async
